In [1]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[12,20,30], [20,30,40],[34,346,34]]

In [6]:
matrixListesi[1][0]

20

In [7]:
np.array(matrixListesi)

array([[ 12,  20,  30],
       [ 20,  30,  40],
       [ 34, 346,  34]])

## arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [11]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ones

In [13]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [14]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [15]:
np.linspace(0,20,30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [16]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## eye

In [17]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [18]:
np.random.randn(8)

array([-0.08953012, -0.72886373,  0.84498556,  0.24784651, -0.29743829,
       -0.31859696, -1.05720723,  0.08022286])

In [19]:
np.random.randn(4,4)

array([[ 1.76230014, -0.48161664, -0.6783171 ,  0.05300439],
       [ 1.75481182,  0.47100111, -1.43962977, -0.68979628],
       [-1.46393603, -2.51817287, -0.45109054, -0.12503196],
       [ 1.520083  , -0.19559521,  1.01617041,  1.33300703]])

In [20]:
np.random.randint(1,10) # int değer döndürüyor

2

In [21]:
np.random.randint(1,10,5)

array([9, 5, 3, 3, 5])

In [22]:
np.random.randint(1,300,5)

array([ 43, 218, 281, 280, 238])

In [23]:
benimNumpyDizim = np.arange(30)

In [24]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
benimRandomDizim = np.random.randint(0,200,30)

In [26]:
benimRandomDizim

array([ 85, 176,   3,  32,  12,  65, 194, 156,  96, 112, 190, 151, 150,
        31, 110,  67, 117, 155,  29, 171,  32, 161,  18,  48,  48, 164,
        98, 148,  40,  21])

## Numpy dizi metodları

In [27]:
benimNumpyDizim.reshape(5,6)  # eleman sayısınca uyan matris e bölebiliyoruz

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
benimNumpyDizim.max()

29

In [29]:
benimRandomDizim.max()

194

In [30]:
benimRandomDizim.min()

3

In [31]:
benimRandomDizim.argmax() # index ini gösteriyor bize

6

In [32]:
benimRandomDizim.argmin()

2

In [33]:
benimNumpyDizim.shape

(30,)

In [34]:
reshapeDizim = benimNumpyDizim.reshape(6,5)

In [35]:
reshapeDizim.shape

(6, 5)