In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
benimDizim[5]

5

In [4]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [5]:
benimDizim[3:8] = -5
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [6]:
baskaDizi = np.arange(0,24)

In [7]:
slicingDizisi = baskaDizi[4:9]
slicingDizisi

array([4, 5, 6, 7, 8])

In [8]:
type(slicingDizisi)

numpy.ndarray

In [9]:
slicingDizisi[:] = 700
slicingDizisi

array([700, 700, 700, 700, 700])

In [10]:
baskaDizi # buradaki değerler değişmi oldu !!

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [11]:
# orjinali etkilenmesin isersek:
ornekDİzi = np.arange(0,24)
ornekDİzi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
ornekDiziKopyasi = ornekDİzi.copy()
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[2:9]
ornekDiziKopyaSlicing

array([2, 3, 4, 5, 6, 7, 8])

In [14]:
ornekDiziKopyaSlicing[:] = 800
ornekDiziKopyaSlicing

array([800, 800, 800, 800, 800, 800, 800])

In [15]:
ornekDiziKopyasi

array([  0,   1, 800, 800, 800, 800, 800, 800, 800,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [16]:
ornekDİzi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [17]:
listem = [[23,14,231], [12,1238,32], [45,63,63]]

In [18]:
benimMatrixDizim = np.array(listem)
benimMatrixDizim

array([[  23,   14,  231],
       [  12, 1238,   32],
       [  45,   63,   63]])

In [19]:
benimMatrixDizim[0]

array([ 23,  14, 231])

In [20]:
benimMatrixDizim[1][2]

32

In [21]:
benimMatrixDizim[1,2] # bunu yazmakla üsttekini yazmak aynı şey

32

In [22]:
benimMatrixDizim[1:, 2] # dersek 1.indexten başla tümü, 2.indexleri yani:

array([32, 63])

In [23]:
benimMatrixDizim[0:,2] # sütunu öylece aldı

array([231,  32,  63])

In [24]:
benimMatrixDizim[2:, 1:]

array([[63, 63]])

In [25]:
benimMatrixDizim[2:, 2:]

array([[63]])

In [26]:
yeniListe = [[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,24]]

In [27]:
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [29]:
yeniMatrix[[0,2,4]] # liste olarak verirsekte bu şekilde getiriyor

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [30]:
yeniMatrix[[1,3,0]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [31]:
yeniBirDizi = np.random.randint(1,100,20)
yeniBirDizi

array([50, 42, 83, 43, 69, 50,  8, 56, 66, 62, 82, 35,  7, 66, 77, 61, 13,
       80, 33, 51])

In [32]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True])

In [33]:
sonucDizisi = yeniBirDizi > 24
sonucDizisi

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True])

In [34]:
yeniBirDizi[sonucDizisi]

array([50, 42, 83, 43, 69, 50, 56, 66, 62, 82, 35, 66, 77, 61, 80, 33, 51])

In [35]:
yeniBirDizi[yeniBirDizi > 24] # filterleme yapıyoruz aslında bir nevi

array([50, 42, 83, 43, 69, 50, 56, 66, 62, 82, 35, 66, 77, 61, 80, 33, 51])

In [36]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
sonDizi + sonDizi # + - * / yapılabilir bu  şekilde

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [38]:
sonDizi # dizimiz değişmedi sonucu başka bir değişkene atamadığımız sürece

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [39]:
kareKok = np.sqrt(sonDizi)
kareKok

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [40]:
np.max(kareKok)

4.795831523312719

In [41]:
np.min(kareKok)

0.0